version: '2'
services:
  web:
    build: .
    depends_on: 
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    environment:
      - MONGO_URI=db/store
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: store
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: